name: Build Whisper-CPP CLI & Stream

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
  workflow_call:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
        type: string

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ inputs.release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags

      - name: Ensure GitHub release exists for tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ inputs.release_tag }}';
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              console.log(`Release for tag ${tag} already exists.`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Creating new release for tag ${tag}.`);
                const release = await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: tag,
                  name: `Harvey Sidecars ${tag}`,
                  body: `Supported platforms for this release: \n- windows-x86_64\n- windows-arm64\n- linux-x86_64\n- linux-arm64\n- macos-x86_64\n- macos-arm64`,
                  draft: false,
                  prerelease: false,
                });
              } else {
                throw error;
              }
            }

  build-and-upload:
    name: Build & Upload Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      SDL2_DIR: "" # Initialize SDL2_DIR to avoid static analysis warnings
      TOOLCHAIN_DIR: "" # Initialize TOOLCHAIN_DIR to avoid static analysis warnings
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            folder: macos-x86_64
            cmake_opts: ""
          - os: macos-14
            folder: macos-arm64
            cmake_opts: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - os: ubuntu-latest
            folder: windows-x86_64
            container: mstorsjo/llvm-mingw
            cmake_opts: ""
          - os: ubuntu-latest
            folder: windows-arm64
            container: mstorsjo/llvm-mingw
            cmake_opts: ""
          - os: ubuntu-latest
            folder: linux-x86_64
            cmake_opts: ""
          - os: ubuntu-latest
            folder: linux-arm64
            cmake_opts: ""
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites (macOS)
        if: runner.os == 'macOS'
        run: brew install sdl2


      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux' && matrix.container == ''
        run: |
          set -e
          if [[ "${{ matrix.folder }}" == "linux-arm64" ]]; then
            # 1. Install host build tools for ARM64 cross-compilation
            sudo apt-get update -y
            sudo apt-get install -y build-essential cmake curl zip

            # 2. Create a self-contained cross-compilation environment for ARM64
            TOOLCHAIN_DIR_PATH="${{ github.workspace }}/arm-gnu-toolchain"
            SDL2_INSTALL_PATH="${{ github.workspace }}/SDL2-install-arm64"
            echo "TOOLCHAIN_DIR=${TOOLCHAIN_DIR_PATH}" >> $GITHUB_ENV
            echo "SDL2_DIR=${SDL2_INSTALL_PATH}" >> $GITHUB_ENV

            # 3. Download and extract the AArch64 toolchain
            TOOLCHAIN_URL="https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz"
            echo "Downloading toolchain..."
            curl -L -o toolchain.tar.xz "${TOOLCHAIN_URL}"
            echo "Extracting toolchain..."
            mkdir -p "${TOOLCHAIN_DIR_PATH}"
            tar -xJf toolchain.tar.xz -C "${TOOLCHAIN_DIR_PATH}" --strip-components=1

            # 4. Download and build SDL2 from source using the cross-compiler
            SDL2_VERSION="2.30.5"
            echo "Downloading SDL2 source..."
            curl -sL "https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-${SDL2_VERSION}.tar.gz" | tar xz
            cd SDL2-${SDL2_VERSION}
            mkdir build && cd build
            echo "Configuring and building SDL2 for aarch64..."
            cmake .. -DCMAKE_C_COMPILER="${TOOLCHAIN_DIR_PATH}/bin/aarch64-none-linux-gnu-gcc" \
                     -DCMAKE_CXX_COMPILER="${TOOLCHAIN_DIR_PATH}/bin/aarch64-none-linux-gnu-g++" \
                     -DCMAKE_INSTALL_PREFIX="${SDL2_INSTALL_PATH}" \
                     -DSDL_STATIC=ON \
                     -DSDL_SHARED=OFF
            make -j$(nproc)
            make install
          else
            # 1. Install host build tools for x86_64 static compilation
            sudo apt-get update -y
            sudo apt-get install -y build-essential cmake curl zip

            # 2. Set up environment for self-contained x86_64 build
            SDL2_INSTALL_PATH="${{ github.workspace }}/SDL2-install-x86_64"
            echo "SDL2_DIR=${SDL2_INSTALL_PATH}" >> $GITHUB_ENV

            # 3. Download and build SDL2 from source using native compilers
            SDL2_VERSION="2.30.5"
            echo "Downloading SDL2 source..."
            curl -sL "https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-${SDL2_VERSION}.tar.gz" | tar xz
            cd SDL2-${SDL2_VERSION}
            mkdir build && cd build
            echo "Configuring and building SDL2 for x86_64..."
            cmake .. -DCMAKE_INSTALL_PREFIX="${SDL2_INSTALL_PATH}" \
                     -DSDL_STATIC=ON \
                     -DSDL_SHARED=OFF
            make -j$(nproc)
            make install
          fi


      - name: Clone whisper.cpp
        run: git clone --depth 1 --branch v1.6.2 https://github.com/ggml-org/whisper.cpp.git whisper.cpp




      - name: Build whisper.cpp
        run: |
          set -ex
          cd whisper.cpp
          rm -rf build
          mkdir build && cd build
          INSTALL_PREFIX="${{ github.workspace }}/whisper-cpp-install/${{ matrix.folder }}"

          # Base CMake options
          CMAKE_OPTS=(
            "-DCMAKE_BUILD_TYPE=Release"
            "-DBUILD_SHARED_LIBS=OFF"
            "-DWHISPER_SDL2=ON"
            "-DWHISPER_OPENBLAS=ON"
            "-DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}"
          )

          # Platform-specific configurations
          if [[ "${{ matrix.folder }}" == "windows-arm64" ]]; then
            apt-get update && apt-get install -y --no-install-recommends ca-certificates curl xz-utils zip
            SDL2_INSTALL_PATH="${{ github.workspace }}/SDL2-install"
            ./../scripts/build-sdl2-mingw.sh aarch64-w64-mingw32 "${SDL2_INSTALL_PATH}"
            TOOLCHAIN_FILE="${{ github.workspace }}/.github/toolchains/aarch64-w64-mingw32.cmake"
            CMAKE_OPTS+=(
              "-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}"
              "-DCMAKE_PREFIX_PATH=${SDL2_INSTALL_PATH}"
              "-DCMAKE_EXE_LINKER_FLAGS=-static -static-libgcc -static-libstdc++ -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -lsetupapi -lksuser -lshell32"
            )
          elif [[ "${{ matrix.folder }}" == "windows-x86_64" ]]; then
            apt-get update && apt-get install -y --no-install-recommends ca-certificates curl xz-utils zip
            SDL2_INSTALL_PATH="${{ github.workspace }}/SDL2-install"
            ./../scripts/build-sdl2-mingw.sh x86_64-w64-mingw32 "${SDL2_INSTALL_PATH}"
            TOOLCHAIN_FILE="${{ github.workspace }}/.github/toolchains/x86_64-w64-mingw32.cmake"
            CMAKE_OPTS+=(
              "-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}"
              "-DCMAKE_PREFIX_PATH=${SDL2_INSTALL_PATH}"
              "-DCMAKE_EXE_LINKER_FLAGS=-static -static-libgcc -static-libstdc++ -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -lsetupapi -lksuser -lshell32"
            )
          elif [[ "${{ matrix.folder }}" == "linux-arm64" ]]; then
            CMAKE_OPTS+=(
              "-DCMAKE_SYSTEM_NAME=Linux"
              "-DCMAKE_SYSTEM_PROCESSOR=aarch64"
              "-DCMAKE_C_COMPILER=${{ env.TOOLCHAIN_DIR }}/bin/aarch64-none-linux-gnu-gcc"
              "-DCMAKE_CXX_COMPILER=${{ env.TOOLCHAIN_DIR }}/bin/aarch64-none-linux-gnu-g++"
              "-DCMAKE_PREFIX_PATH=${{ env.SDL2_DIR }}"
              "-DCMAKE_EXE_LINKER_FLAGS=-static"
            )
          elif [[ "${{ matrix.folder }}" == "linux-x86_64" ]]; then
            CMAKE_OPTS+=(
              "-DCMAKE_PREFIX_PATH=${{ env.SDL2_DIR }}"
              "-DCMAKE_EXE_LINKER_FLAGS=-static"
            )
          elif [[ "${{ matrix.folder }}" == "macos-arm64" ]]; then
            CMAKE_OPTS+=("-DCMAKE_OSX_ARCHITECTURES=arm64")
          elif [[ "${{ matrix.folder }}" == "macos-x86_64" ]]; then
            CMAKE_OPTS+=("-DCMAKE_OSX_ARCHITECTURES=x86_64")
          fi

          cmake .. "${CMAKE_OPTS[@]}"
          make -j$(nproc) main stream
          make install

      - name: List installed whisper-cpp files (Debug)
        run: |
          INSTALL_PREFIX="${{ github.workspace }}/whisper-cpp-install/${{ matrix.folder }}"
          echo "Listing contents of ${INSTALL_PREFIX}:"
          ls -R "${INSTALL_PREFIX}" || true

      - name: Prepare assets for release
        id: prepare_assets
        run: |
          mkdir -p release_assets
          INSTALL_PREFIX="${{ github.workspace }}/whisper-cpp-install/${{ matrix.folder }}"
          if [[ "${{ matrix.folder }}" == "windows-x86_64" || "${{ matrix.folder }}" == "windows-arm64" ]]; then
            cp "${INSTALL_PREFIX}/bin/main.exe" release_assets/whisper-cli.exe
            cp "${INSTALL_PREFIX}/bin/stream.exe" release_assets/whisper-stream.exe
          else
            cp "${INSTALL_PREFIX}/bin/main" release_assets/whisper-cli
            cp "${INSTALL_PREFIX}/bin/stream" release_assets/whisper-stream
          fi
          echo "--- Prepared assets ---"
          ls -lh release_assets


      - name: Upload assets (macOS/Linux)
        if: runner.os != 'Windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          cd release_assets

          # Create zip archive
          ZIP_ASSET="whisper-sidecars-${{ matrix.folder }}.zip"
          zip "${ZIP_ASSET}" *

          # Create checksum
          shasum -a 256 "${ZIP_ASSET}" > "${ZIP_ASSET}.sha256"

          # Upload assets
          gh release upload ${{ needs.create-release.outputs.release_tag }} "${ZIP_ASSET}" "${ZIP_ASSET}.sha256" --clobber --repo ${{ github.repository }}

      - name: Upload assets (Windows)
        if: runner.os == 'Windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          cd release_assets

          # Create zip archive
          ZIP_ASSET="whisper-sidecars-${{ matrix.folder }}.zip"
          zip "${ZIP_ASSET}" *

          # Create checksum
          shasum -a 256 "${ZIP_ASSET}" > "${ZIP_ASSET}.sha256"

          # Upload assets
          gh release upload ${{ needs.create-release.outputs.release_tag }} "${ZIP_ASSET}" "${ZIP_ASSET}.sha256" --clobber --repo ${{ github.repository }}
