name: Build whisper.cpp Tools

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
  workflow_call:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
        type: string

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ inputs.release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure GitHub release exists for tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ inputs.release_tag }}';
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              console.log(`Release for tag ${tag} already exists.`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Creating new release for tag ${tag}.`);
                await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: tag,
                  name: `Harvey Sidecars ${tag}`,
                  body: `Automated build of whisper.cpp tools.`,
                  draft: false,
                  prerelease: false,
                });
              } else {
                throw error;
              }
            }

  build-and-upload:
    name: Build & Upload Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    env:
      SDL2_DIR: "${{ github.workspace }}/SDL2-install"
      TOOLCHAIN_DIR: ""
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            folder: macos-x86_64
            cmake_opts: ""
          - os: macos-14
            folder: macos-arm64
            cmake_opts: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - os: windows-latest
            folder: windows-x86_64
            cmake_opts: "-G \"Unix Makefiles\""
          - os: windows-latest
            folder: windows-arm64
            cmake_opts: "-G \"Unix Makefiles\""
          - os: ubuntu-latest
            folder: linux-x86_64
            cmake_opts: ""
          - os: ubuntu-latest
            folder: linux-arm64
            cmake_opts: ""
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake sdl2

      - name: Install prerequisites (Windows)
        if: runner.os == 'Windows'
        run: choco install zip

      - name: Setup MSYS2 environment (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.folder == 'windows-arm64' && 'CLANGARM64' || 'CLANG64' }}
          update: true
          install: make cmake mingw-w64-clang-aarch64-toolchain mingw-w64-clang-x86_64-toolchain

      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          set -e
          if [[ "${{ matrix.folder }}" == "linux-arm64" ]]; then
            sudo apt-get update -y
            sudo apt-get install -y build-essential cmake curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            TOOLCHAIN_DIR_PATH="${{ github.workspace }}/arm-gnu-toolchain"
            SDL2_INSTALL_PATH="${{ github.workspace }}/SDL2-install-arm64"
            echo "TOOLCHAIN_DIR=${TOOLCHAIN_DIR_PATH}" >> $GITHUB_ENV
            echo "SDL2_DIR=${SDL2_INSTALL_PATH}" >> $GITHUB_ENV
            TOOLCHAIN_URL="https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz"
            curl -L -o toolchain.tar.xz "${TOOLCHAIN_URL}"
            mkdir -p "${TOOLCHAIN_DIR_PATH}"
            tar -xJf toolchain.tar.xz -C "${TOOLCHAIN_DIR_PATH}" --strip-components=1
            SDL2_VERSION="2.30.5"
            curl -sL "https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-${SDL2_VERSION}.tar.gz" | tar xz
            cd SDL2-${SDL2_VERSION}
            mkdir build && cd build
            cmake .. -DCMAKE_C_COMPILER="${TOOLCHAIN_DIR_PATH}/bin/aarch64-none-linux-gnu-gcc" \
                     -DCMAKE_CXX_COMPILER="${TOOLCHAIN_DIR_PATH}/bin/aarch64-none-linux-gnu-g++" \
                     -DCMAKE_INSTALL_PREFIX="${SDL2_INSTALL_PATH}" \
                     -DSDL_STATIC=ON -DSDL_SHARED=OFF
            make -j$(nproc)
            make install
            cd ../..
          else
            sudo apt-get update -y
            sudo apt-get install -y build-essential cmake curl libsdl2-dev
          fi

      - name: Build SDL2 (Windows only)
        if: runner.os == 'Windows'
        run: |
          SDL2_VERSION="2.30.5"
          echo "Building SDL2 from source for ${{ matrix.folder }}"
          curl -sL "https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-${SDL2_VERSION}.tar.gz" | tar xz
          cd SDL2-${SDL2_VERSION}
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_INSTALL_PREFIX="${{ env.SDL2_DIR }}" \
                   -DSDL_STATIC=ON \
                   -DSDL_SHARED=OFF \
                   ${{ matrix.cmake_opts }}
          make -j$(nproc)
          make install
          cd ../..

      - name: Clone whisper.cpp
        run: git clone --depth 1 --branch v1.6.2 https://github.com/ggml-org/whisper.cpp.git whisper.cpp

      - name: Build whisper.cpp
        run: |
          mkdir -p whisper.cpp/build
          cd whisper.cpp/build
          
          CMAKE_FLAGS=(
            -DCMAKE_BUILD_TYPE=Release
            -DBUILD_SHARED_LIBS=OFF
            -DWHISPER_BUILD_EXAMPLES=ON
            -DWHISPER_BUILD_TESTS=OFF
            -DWHISPER_SDL2=ON
            -DCMAKE_PREFIX_PATH="${{ env.SDL2_DIR }}"
            ${{ matrix.cmake_opts }}
          )

          if [[ "${{ matrix.folder }}" == "linux-arm64" ]]; then
            CMAKE_FLAGS+=(
              -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/whisper.cpp/cmake/toolchains/aarch64-linux-gnu.cmake
              -DCMAKE_C_COMPILER="${{ env.TOOLCHAIN_DIR }}/bin/aarch64-none-linux-gnu-gcc" 
              -DCMAKE_CXX_COMPILER="${{ env.TOOLCHAIN_DIR }}/bin/aarch64-none-linux-gnu-g++"
            )
          fi

          cmake .. "${CMAKE_FLAGS[@]}"
          
          make -j$(nproc) main stream

      - name: Package Binaries
        id: package_binaries
        run: |
          echo "Packaging binaries for ${{ matrix.folder }} on ${{ matrix.os }}"
          ASSET_DIR="${{ github.workspace }}/release_assets"
          mkdir -p "${ASSET_DIR}"
          
          cd "${{ github.workspace }}/whisper.cpp/build/bin"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # SDL2.dll is needed at runtime for the stream executable
            cp "${{ env.SDL2_DIR }}/bin/SDL2.dll" "${ASSET_DIR}/"
            mv main.exe "${ASSET_DIR}/whisper-cli.exe"
            mv stream.exe "${ASSET_DIR}/whisper-stream.exe"
          else
            mv main "${ASSET_DIR}/whisper-cli"
            mv stream "${ASSET_DIR}/whisper-stream"
          fi

          cd "${ASSET_DIR}"
          ASSET_NAME="whisper-tools-${{ matrix.folder }}"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ASSET_FILENAME="${ASSET_NAME}.zip"
            zip -r "${ASSET_FILENAME}" .
          else
            ASSET_FILENAME="${ASSET_NAME}.tar.gz"
            tar -czvf "../${ASSET_FILENAME}" .
          fi

          echo "Created package: ${ASSET_FILENAME}"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "ASSET_PATH=${ASSET_DIR}/${ASSET_FILENAME}" >> $GITHUB_OUTPUT
          else
            echo "ASSET_PATH=${ASSET_DIR}/../${ASSET_FILENAME}" >> $GITHUB_OUTPUT
          fi
          echo "ASSET_NAME=${ASSET_FILENAME}" >> $GITHUB_OUTPUT

      - name: Upload Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading ${{ steps.package_binaries.outputs.ASSET_NAME }} to release ${{ needs.create-release.outputs.release_tag }}"
          gh release upload ${{ needs.create-release.outputs.release_tag }} ${{ steps.package_binaries.outputs.ASSET_PATH }} --clobber