name: Build whisper.cpp Shared Libraries

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
  workflow_call:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
        type: string

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ inputs.release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure GitHub release exists for tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ inputs.release_tag }}';
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              console.log(`Release for tag ${tag} already exists.`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Creating new release for tag ${tag}.`);
                await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: tag,
                  name: `Harvey Sidecars ${tag}`,
                  body: `Automated build of whisper.cpp shared libraries.`, 
                  draft: false,
                  prerelease: false,
                });
              } else {
                throw error;
              }
            }

  build-and-upload:
    name: Build & Upload Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    env:
      SDL2_DIR: ""
      TOOLCHAIN_DIR: ""
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            folder: macos-x86_64
            cmake_opts: ""
          - os: macos-14
            folder: macos-arm64
            cmake_opts: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - os: windows-latest
            folder: windows-x86_64
            cmake_opts: "-G \"Unix Makefiles\""
          - os: windows-latest
            folder: windows-arm64
            cmake_opts: "-G \"Unix Makefiles\""
          - os: ubuntu-latest
            folder: linux-x86_64
            cmake_opts: ""
          - os: ubuntu-latest
            folder: linux-arm64
            cmake_opts: ""
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites (macOS)
        if: runner.os == 'macOS'
        run: brew install sdl2

      - name: Setup MSYS2 environment (Windows ARM64)
        if: matrix.folder == 'windows-arm64'
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: make cmake mingw-w64-clang-aarch64-toolchain

      - name: Setup MSYS2 environment (Windows x86_64)
        if: matrix.folder == 'windows-x86_64'
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: make cmake mingw-w64-clang-x86_64-toolchain

      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake curl libsdl2-dev

      - name: Install prerequisites (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          SDL2_VERSION="2.30.5"
          echo "Building SDL2 from source for ${{ matrix.folder }}"
          curl -sL "https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-${SDL2_VERSION}.tar.gz" | tar xz
          cd SDL2-${SDL2_VERSION}
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/SDL2-install" \
                   -DSDL_STATIC=OFF \
                   -DSDL_SHARED=ON \
                   ${{ matrix.cmake_opts }}
          make -j$(nproc)
          make install
          echo "SDL2_DIR=${{ github.workspace }}/SDL2-install" >> $GITHUB_ENV
          cd ../..

      - name: Clone whisper.cpp
        run: git clone --depth 1 --branch v1.6.2 https://github.com/ggml-org/whisper.cpp.git whisper.cpp

      - name: Build whisper.cpp
        run: |
          mkdir -p whisper.cpp/build
          cd whisper.cpp/build
          INSTALL_PREFIX="${{ github.workspace }}/whisper-cpp-install/${{ matrix.folder }}"
          
          CMAKE_FLAGS=(
            -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}"
            -DCMAKE_BUILD_TYPE=Release
            -DBUILD_SHARED_LIBS=ON
            -DWHISPER_SDL2=ON
            -DBUILD_EXAMPLES=ON # Keep examples to get whisper-cli and whisper-stream
            ${{ matrix.cmake_opts }}
          )

          if [[ "${{ runner.os }}" != "macOS" ]]; then
            CMAKE_FLAGS+=(-DCMAKE_PREFIX_PATH=${{ env.SDL2_DIR }})
          fi
          
          cmake .. "${CMAKE_FLAGS[@]}"
          
          make -j$(nproc)
          make install

      - name: Package Binaries
        id: package_binaries
        run: |
          echo "Packaging binaries for ${{ matrix.folder }} on ${{ matrix.os }}"
          INSTALL_DIR="${{ github.workspace }}/whisper-cpp-install/${{ matrix.folder }}"
          cd "${INSTALL_DIR}"
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ASSET_NAME="whisper-cpp-${{ matrix.folder }}.zip"
            zip -r "${ASSET_NAME}" .
          else
            ASSET_NAME="whisper-cpp-${{ matrix.folder }}.tar.gz"
            tar -czvf "${ASSET_NAME}" .
          fi
          
          echo "Created package: ${ASSET_NAME}"
          echo "ASSET_PATH=${INSTALL_DIR}/${ASSET_NAME}" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=${ASSET_NAME}" >> $GITHUB_OUTPUT

      - name: Upload Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading ${{ steps.package_binaries.outputs.ASSET_NAME }} to release ${{ needs.create-release.outputs.release_tag }}"
          gh release upload ${{ needs.create-release.outputs.release_tag }} ${{ steps.package_binaries.outputs.ASSET_PATH }} --clobber