name: Build FFmpeg Windows

on:
  workflow_dispatch:

jobs:
  build-ffmpeg:
    runs-on: windows-latest

    steps:
      - name: Build FFmpeg
        uses: rt-ffmpeg/build-ffmpeg@v1
        with:
          ffmpeg-version: '6.0'
          configure-flags: '--enable-shared --disable-static --disable-gpl --disable-nonfree --disable-ffplay --disable-ffprobe --disable-doc --disable-autodetect --enable-zlib --enable-iconv --enable-d3d11va --disable-libmp3lame'

      - name: Upload FFmpeg build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-x86_64-windows
          path: artifacts
