name: Test Pre-built Sidecars

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # The release tag from which to download the test binaries
  RELEASE_TAG: "v0.2.0"

jobs:
  test_transcription:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13 # Intel Mac
            arch: macos-x86_64
          - os: macos-14 # Apple Silicon
            arch: macos-arm64
          - os: windows-latest
            arch: windows-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Binaries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          # Define the file extension for Windows
          EXT=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            EXT=".exe"
          fi

          # Define the asset names based on the matrix
          FFMPEG_ASSET="ffmpeg-${{ matrix.arch }}${EXT}"
          WHISPER_ASSET="whisper-cpp-${{ matrix.arch }}${EXT}"
          
          echo "Downloading ${FFMPEG_ASSET} and ${WHISPER_ASSET}..."

          # Download the main binaries
          gh release download ${{ env.RELEASE_TAG }} --pattern "${FFMPEG_ASSET}" --pattern "${WHISPER_ASSET}" --clobber
          
          # Download SDL2.dll for Windows
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            gh release download ${{ env.RELEASE_TAG }} --pattern "SDL2.dll" --clobber
          fi
          
          # Make the binaries executable on non-Windows runners
          if [[ "${{ runner.os }}" != "Windows" ]]; then
            chmod +x "${FFMPEG_ASSET}"
            chmod +x "${WHISPER_ASSET}"
          fi

          echo "--- Downloaded Files ---"
          ls -la

      - name: Download Whisper Model
        run: |
          echo "Downloading ggml-base.en.bin model..."
          # The download script from whisper.cpp just curls this URL
          curl -L -o ggml-base.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin

      - name: Convert Audio to WAV with FFmpeg
        run: |
          EXT=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            EXT=".exe"
          fi
          FFMPEG_EXE="./ffmpeg-${{ matrix.arch }}${EXT}"

          echo "Converting audio file with ${FFMPEG_EXE}..."
          "$FFMPEG_EXE" -i sample_data/audio.mp3 -ar 16000 -ac 1 -c:a pcm_s16le audio.wav

      - name: Transcribe with whisper.cpp
        run: |
          EXT=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            EXT=".exe"
          fi
          WHISPER_EXE="./whisper-cpp-${{ matrix.arch }}${EXT}"
          
          echo "--- Transcribing on ${{ matrix.os }} using ${WHISPER_EXE} ---"
          "$WHISPER_EXE" -m ggml-base.en.bin -f audio.wav
