name: Update Whisper-CPP Sidecar

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
  workflow_call:
    inputs:
      release_tag:
        description: 'Git tag to use for the release (must already exist)'
        required: true
        type: string

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ inputs.release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags

      - name: Ensure GitHub release exists for tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ inputs.release_tag }}';
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              console.log(`Release for tag ${tag} already exists.`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Creating new release for tag ${tag}.`);
                const release = await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: tag,
                  name: `Sidecars ${tag}`,
                  body: `Automated build of whisper.cpp sidecars (whisper-cli and whisper-stream).`,
                  draft: false,
                  prerelease: false,
                });
              } else {
                throw error;
              }
            }

  build-and-upload:
    name: Build & Upload Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            folder: macos-x86_64
            cmake_opts: ""
          - os: macos-14
            folder: macos-arm64
            cmake_opts: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - os: windows-latest
            folder: windows-x86_64
            cmake_opts: ""
          - os: windows-latest
            folder: windows-arm64
            cmake_opts: "-A arm64"
          - os: ubuntu-latest
            folder: linux-x86_64
            cmake_opts: ""
          - os: ubuntu-latest
            folder: linux-arm64
            cmake_opts: "-DCMAKE_TOOLCHAIN_FILE=../toolchain-aarch64-linux-gnu.cmake -DGGML_ARM_NEON=ON"
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites (macOS)
        if: runner.os == 'macOS'
        run: brew install sdl2

      - name: Install prerequisites (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          if [[ "${{ matrix.folder }}" == "windows-arm64" ]]; then
            ./vcpkg install sdl2:arm64-windows
          else
            ./vcpkg install sdl2:x64-windows
          fi
          cd ..

      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          if [[ "${{ matrix.folder }}" == "linux-arm64" ]]; then
            set -e
            # Download and set up a self-contained aarch64 toolchain instead of using apt
            TOOLCHAIN_URL="https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz"
            curl -sL ${TOOLCHAIN_URL} | tar -xJ
            TOOLCHAIN_DIR=$(pwd)/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu
            
            # Create a toolchain file for building SDL2
            echo "set(CMAKE_SYSTEM_NAME Linux)" > toolchain-sdl2.cmake
            echo "set(CMAKE_SYSTEM_PROCESSOR aarch64)" >> toolchain-sdl2.cmake
            echo "set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-gcc)" >> toolchain-sdl2.cmake
            echo "set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-g++)" >> toolchain-sdl2.cmake
            
            # Build SDL2 from source for arm64, installing it into our toolchain directory
            SDL2_VERSION="2.30.5"
            curl -sL "https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-${SDL2_VERSION}.tar.gz" | tar xz
            cd SDL2-${SDL2_VERSION}
            mkdir build && cd build
            cmake .. -DCMAKE_TOOLCHAIN_FILE=../../toolchain-sdl2.cmake \
                      -DCMAKE_INSTALL_PREFIX=${TOOLCHAIN_DIR}/aarch64-linux-gnu \
                      -DSDL_STATIC=ON \
                      -DSDL_SHARED=OFF
            make -j$(nproc)
            make install
            cd ../..
          else
            sudo apt-get update -y
            sudo apt-get install -y libsdl2-dev
          fi

      - name: Clone whisper.cpp
        run: git clone --depth 1 https://github.com/ggml-org/whisper.cpp.git whisper.cpp

      - name: Create toolchain file for linux-arm64
        if: matrix.folder == 'linux-arm64'
        run: |
          TOOLCHAIN_DIR=$(pwd)/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu
          echo "set(CMAKE_SYSTEM_NAME Linux)" > whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_SYSTEM_PROCESSOR aarch64)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-gcc)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-g++)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR}/aarch64-linux-gnu)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake
          echo "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)" >> whisper.cpp/toolchain-aarch64-linux-gnu.cmake

      - name: Build whisper-cpp
        run: |
          if [[ "${{ matrix.folder }}" == "linux-arm64" ]]; then
            TOOLCHAIN_DIR=$(pwd)/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu
            export PKG_CONFIG_PATH=${TOOLCHAIN_DIR}/aarch64-linux-gnu/lib/pkgconfig
            export PATH=${TOOLCHAIN_DIR}/bin:${PATH}
          fi
          mkdir -p whisper.cpp/build
          cd whisper.cpp/build
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake ${{ matrix.cmake_opts }}
          else
            cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON ${{ matrix.cmake_opts }}
          fi
          cmake --build . --config Release

      - name: Prepare assets for release
        id: prepare_assets
        run: |
          mkdir -p release_assets
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp whisper.cpp/build/bin/Release/whisper-cli.exe release_assets/whisper-cli.exe
            cp whisper.cpp/build/bin/Release/whisper-stream.exe release_assets/whisper-stream.exe
            if [[ "${{ matrix.folder }}" == "windows-arm64" ]]; then
              cp vcpkg/installed/arm64-windows/bin/SDL2.dll release_assets/SDL2.dll
            else
              cp vcpkg/installed/x64-windows/bin/SDL2.dll release_assets/SDL2.dll
            fi
          else
            cp whisper.cpp/build/bin/whisper-cli release_assets/whisper-cli
            cp whisper.cpp/build/bin/whisper-stream release_assets/whisper-stream
          fi
          echo "--- Prepared assets ---"
          ls -lh release_assets

      - name: Rename, checksum, and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          cd release_assets

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            CLI_ASSET="whisper-cli-${{ matrix.folder }}.exe"
            STREAM_ASSET="whisper-stream-${{ matrix.folder }}.exe"
            mv whisper-cli.exe "${CLI_ASSET}"
            mv whisper-stream.exe "${STREAM_ASSET}"

            sha256sum "${CLI_ASSET}" > "${CLI_ASSET}.sha256"
            sha256sum "${STREAM_ASSET}" > "${STREAM_ASSET}.sha256"
            
            gh release upload ${{ needs.create-release.outputs.release_tag }} "${CLI_ASSET}" "${CLI_ASSET}.sha256" "${STREAM_ASSET}" "${STREAM_ASSET}.sha256" SDL2.dll --clobber
          else
            CLI_ASSET="whisper-cli-${{ matrix.folder }}"
            STREAM_ASSET="whisper-stream-${{ matrix.folder }}"
            mv whisper-cli "${CLI_ASSET}"
            mv whisper-stream "${STREAM_ASSET}"

            shasum -a 256 "${CLI_ASSET}" > "${CLI_ASSET}.sha256"
            shasum -a 256 "${STREAM_ASSET}" > "${STREAM_ASSET}.sha256"

            gh release upload ${{ needs.create-release.outputs.release_tag }} "${CLI_ASSET}" "${CLI_ASSET}.sha256" "${STREAM_ASSET}" "${STREAM_ASSET}.sha256" --clobber
          fi
