name: Update Translator Sidecar

on:
  workflow_call:
    inputs:
      release_tag:
        description: 'The release tag to use for artifacts'
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-translator-sidecar:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]
        include:
          - os: ubuntu-latest
            pkg_target: node20-linux-x64
            asset_name_suffix: "linux-x86_64"
            executable_extension: ""
          - os: macos-latest
            pkg_target: node20-macos-x64
            asset_name_suffix: "macos-x86_64"
            executable_extension: ""
          - os: windows-latest
            pkg_target: node20-win-x64
            asset_name_suffix: "windows-x86_64"
            executable_extension: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pkg
        run: npm install -g pkg

      - name: Install sidecar dependencies
        run: npm install
        working-directory: translator

      - name: Build translator-sidecar
        run: pkg translator/translator.mjs --targets ${{ matrix.pkg_target }} --output translator/translator-sidecar-${{ matrix.asset_name_suffix }}${{ matrix.executable_extension }}
        working-directory: translator

      - name: Calculate SHA256 hash
        id: hash
        run: |
          BINARY_PATH="translator/translator-sidecar-${{ matrix.asset_name_suffix }}${{ matrix.executable_extension }}"
          HASH=$(sha256sum $BINARY_PATH | awk '{print $1}')
          echo "sha256_hash=$HASH" >> $GITHUB_OUTPUT
          echo "$HASH" > $BINARY_PATH.sha256
        working-directory: translator
        shell: bash

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.release_tag }}
          files: |
            translator/translator-sidecar-${{ matrix.asset_name_suffix }}${{ matrix.executable_extension }}
            translator/translator-sidecar-${{ matrix.asset_name_suffix }}${{ matrix.executable_extension }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
